version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: classflow_db
      POSTGRES_USER: classflow_user
      POSTGRES_PASSWORD: classflow_password
    ports:
      - "5432:5432"
    networks:
      - classflow_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - classflow_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://classflow_user:classflow_password@db:5432/classflow_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - classflow_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - classflow_network

  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ai_service:/app
    environment:
      - FLASK_ENV=development
    networks:
      - classflow_network

volumes:
  postgres_data:
  media_volume:

networks:
  classflow_network:
    driver: bridge
