# Generated by Django 4.2.7 on 2025-08-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=200)),
                ('curriculum_type', models.CharField(choices=[('cbc', 'CBC (Rwanda)'), ('cambridge_igcse', 'Cambridge (IGCSE)'), ('cambridge_a_level', 'Cambridge (A Level)'), ('montessori', 'Montessori'), ('other', 'Other - Specify')], max_length=20)),
                ('other_curriculum_details', models.TextField(blank=True)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('number_of_terms', models.IntegerField(choices=[(2, '2 Terms'), (3, '3 Terms')])),
                ('current_term', models.IntegerField(choices=[(1, 'Term 1'), (2, 'Term 2'), (3, 'Term 3')])),
                ('grading_scale_type', models.CharField(choices=[('percentage', 'Percentage'), ('letter_grades', 'Letter Grades'), ('competency_based', 'Competency-Based')], max_length=20)),
                ('grading_scale_details', models.JSONField(default=dict)),
                ('default_notification_language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('rw', 'Kinyarwanda')], default='en', max_length=5)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('school_website', models.URLField(blank=True)),
                ('vision_mission', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Holiday',
                'verbose_name_plural': 'School Holidays',
                'db_table': 'school_holidays',
                'unique_together': {('school', 'date')},
            },
        ),
    ]
